### PR TITLE
fix django 1.9 router registry

### PR DESCRIPTION
**Pull request by boblefrag**

### CODE REVIEW

**Comment by alanjds** [comment]
Hi.

Could you please expand your bug report?

Thanks.

**Comment by boblefrag** [comment]
Yes sure. With Django 1.9, with : 

```parent_registry = [registered for registered in self.parent_router.registry if registered[0] == self.parent_prefix]```
no registries are found.
but with : 
```parent_registry = self.parent_router.registry```
It works.

My code is something like this:
```python
router = SimpleRouter()
router.register(r'endpoint', AViewSet, base_name='api-myviewset')
sub_router = NestedRouter(router, r'sub', lookup="id")
sub_router.register(r'sub', AnotherViewSet, base_name='api-myviewset-sub')
```
Don't hesitate to ask if you have any other questions about this patch

**Comment by alanjds** [comment]
Hi, @boblefrag.

I just merged your branch into [some other](https://github.com/alanjds/drf-nested-routers/compare/drf-332) that tests against Django 1.9. It fails at the same tests as before, as seem here:

[Tests with Django 1.9 and DRF 3.3 **without your patch**](https://travis-ci.org/alanjds/drf-nested-routers/builds/126176027):
screen shot 2016-05-27 at 11 10 49

[Same tests **with your patch**](https://travis-ci.org/alanjds/drf-nested-routers/builds/133382495):
screen shot 2016-05-27 at 11 11 15

I believe you and understand that if you made a PR is because it matters, but I see no change.

Can you please add some test? If not, I will merge anyway, but will not release until some people confirms that it does not breaks his existing working apps.

**Comment by boblefrag** [comment]
Thank you very much . I will add tests on this to let you see what's going on I'll try to issue one more commit in the next week

**Comment by auvipy** [comment]
@alanjds probably you have to take care of this as @boblefrag seems to be busy with other stuff. IMO after merging some on hold PR you could go for a new release :)

**Comment by alanjds** [comment]
#91 Integrates fixes for the issue raised here, and others. Closed here. 

Please reopen if still broken, if possible providing new tests to be included, as #91 maybe already tests this issue.

**Pull request closed without merging**
