### PR TITLE
Update classifiers

### PR DESCRIPTION
**Pull request by morenol**
In this PR I updated the classifiers and the readme with the versions that are used in the tests.

This is made with the intention to help you to create a new Pypi release

### CODE REVIEW

**Comment by morenol** [comment]
Hi @alanjds, I noticed that the travis health checks are not displayed in this PR.

This PR fixes the tests for python3, should we keep the support for python2? if that is the case we should use a compatible version of pytest.

On the other hand, let me know and I remove python2 from the classifiers and also from readme, travis and tox files

**Comment by alanjds** [comment]
This is strange. I am also wondering what happened with Travis.

I am ok EOLing Py27. The last LTS version of Django supporting 2.7 EOLed on April 2020 anyway.

**Comment by alanjds** [comment]
I just merged some pyup PRs. Can you please update your branch from the new master?

I will keep a look on Travis in the meantime.

**Comment by morenol** [comment]
@alanjds Done!

**Comment by morenol** [comment]
Hi @alanjds, any news on this?

**Pull request closed without merging**
