### PR TITLE
    add NestedHyperlinkedModelSerializer, the nested version of HyperlinkedModelSerializer

### PR DESCRIPTION
**Pull request by c17r**
HyperlinkedModelSerializer allows a sub-resource to be returned as a list of semi-details along with a `url` field to get the full details. HyperlinkedModelSerializer suffers the same fate as everything else in DRF in that it can't construct a URL with compound keys. The nested equivalent, NestedHyperlinkedModelSerializer, fixes that.

### CODE REVIEW

**Comment by c17r** [comment]
Interesting, it worked locally.  I'll fiddle with the test setup to get it working under tox/travis.

**Comment by c17r** [comment]
The only thing I haven't done is put some documentation in because I wasn't sure where to put it with README.md, README.rst, and docs/index.md.  Tell me where you'd like it and I'll add the commit for it.

**Comment by alanjds** [comment]
Thanks! ``README.md`` is ok. The others are only placeholders for now.

The code looks good for me. Will review again with more time later, but thanks again!

**Comment by AncAinu** [comment]
Please make this merge, it looks exactly what everyone is waiting for

**Comment by alanjds** [comment]
Thanks @c17r for the code and @AncAinu for the nudge.

**Pull request merged**
