### PR TITLE
NestedViewsetMixin filters parent

### PR DESCRIPTION
**Pull request by alanjds**
Also allows the creation (POST) of children to not include the parent lookup field, as it is already present on the URL.

### CODE REVIEW

**Comment by Amoki** [comment]
This is a very nice PR :D
We implemented many of those features in our API and plan to migrate to this PR once it's merged. Your code is way cleaner.

Listing objects will return an empty list if parents don't exist instead of a 404.
As a workaround, we check the existence of the parent before calling the `list` method. It costs one more SQL query but we can send a 404 if the parent does not exist.

**Review by c17r — APPROVED** [review]

**Comment by alanjds** [comment]
> We implemented many of those features in our API and plan to migrate to this PR once it's merged.

Yesterday I deployed a pre-release version [0.93.0.dev0](https://pypi.org/project/drf-nested-routers/0.93.0.dev0/) that you can pin on your requirements, yet is not considered the "latest release" on PyPI. Would be helpful you or anyone else can provide feedback on it.

> Your code is way cleaner.

Yeah, I wanted to clean the package from a while. _Right now_ am rebuilding an internal project in the company and used the opportunity to generalize some workarounds into this PR.

Btw, if you know a good Front End dev, we are looking for some :wink:: https://stackoverflow.com/jobs/452407/senior-front-end-developer-poly-swarm-technologies-inc

> Listing objects will return an empty list if parents don't exist instead of a 404.

I do not know if I understood the context here. You mean that `/foo/{pk}/bar/` will return an empty 200 instead of a 400 if no Foo exists with {pk} ?

> As a workaround, we check the existence of the parent before calling the `list` method. It costs one more SQL query but we can send a 404 if the parent does not exist.

Well, the serializer is already doing this SQL query IIUC, so my approach will be caching this SQL query if very frequent. Another workaround I got used to save this query to parent is to hack the child queryset to also fetch the parent fields that I need: (example ahead)
```py
class NameserverViewSet(NestedViewSetMixin, viewsets.ModelViewSet):
    # Hack: fetch "only" all Nameserver fields and some Domain fields
    queryset = Nameserver.objects.all().select_related('domain').only(
        *[f.name for f in Nameserver._meta.fields],
        'domain__name',
    )
```

If you have more hacks needed, please open issues so everybody can know the current limitations. Or even better if you can open a PR instead :sunglasses:

**Comment by Amoki** [comment]
Sorry, I don't know any senior front end dev looking for a job!


> I do not know if I understood the context here. You mean that /foo/{pk}/bar/ will return an empty 200 instead of a 400 if no Foo exists with {pk} ?

Yes, but I'm not sure to understand your workaround. I'll try and see what happens!

**Comment by alanjds** [comment]
Heads up: This PR has included in the just-released version 0.93.3: https://pypi.org/project/drf-nested-routers/0.93.3/

Thanks for the comments and reviews.

**Pull request merged**
