### PR TITLE
Fix to use get_serializer_class method instead of serializer_class

### LINKED ISSUE #133: NestedViewSetMixin should use `get_serializer_class` method instead of `serializer_class`
GenericAPIView and GenericViewSet implement `get_serializer_class` method to provide dynamic behavior of serializer class. Its documentation is here: https://www.django-rest-framework.org/api-guide/generic-views/#get_serializer_classself

This change do not affect default behavior of this module. `get_serializer_class` returns its class attribute (`serializer_class`) by default. 

I patched this, but in my environment, test with `tox` always fail with or without any changes. May I open the PR?

### PR DESCRIPTION
**Pull request by pddg**
fix #133 

It's a bit of a change :)

### CODE REVIEW

**Comment by alanjds** [comment]
Looks like updates on the pytest plugins broke our tests :/

The PR should wait this to be fixed. Sorry.

**Comment by alanjds** [comment]
Finally fixed the tests on `master`. Got problems with unpinned pytest-* versions

**Comment by pddg** [comment]
I rebased this PR onto current master.

**Comment by alanjds** [comment]
Thanks for the issue, the PR and the patience, @pddg.

**Pull request merged**
