### PR TITLE
Update viewsets.py

### PR DESCRIPTION
**Pull request by Moulde**
From https://github.com/alanjds/drf-nested-routers/issues/149
Fixes exception in drf-yasg / django-rest-swagger

### CODE REVIEW

**Comment by alanjds** [comment]
Thanks a lot, @Moulde !

**Comment by Moulde** [comment]
No problem :) Glad to help! - But please note that I have not tested it (yet).
I only stumbled upon the exception in my project, found the issue and from looking at the code it looks right.

I will test later today and let you know if it's solved.

**Comment by Moulde** [comment]
My issue is that my nested viewset is attempting to filter on the parent id.

```
class NestedModelViewSet(mixins.ListModelMixin, 
                mixins.DestroyModelMixin,
                GenericViewSet):
    serializer_class = serializers.NestedModelDetailSerializer
    queryset = NestedModel.objects.all()

    def get_queryset(self):
        return NestedModel.objects.filter(message=self.kwargs['parent_pk'])
```

But the parent_pk does not exist in the kwargs - so when drf-yasg is attempting to instantiate it, it fails.

But... the change i made does not seem to fix this issue...
So either A. the fix does not work, or B. I have misunderstood what issue #149 actually fixes..

drf-yasg says to fix this issue by checking if a specific property 'swagger_fake_view' exists, and if it does, don't run the query.

Sorry about the confusion!

**Comment by alanjds** [comment]
No problem.

I accepted the PR because it had not broken other tests and seemed that it fixed a thing reported on other issue.

Anyway, I suggest you to try to reproduce the error using an automated test. This will make easier/faster to iterate over your tries to fix it. And will make sure that this does not came back, after really fixed.

Thanks again, Alan.

**Pull request merged**
