### PR TITLE
make NestedSimpleRouter recursion possible - including unittest based up...

### PR DESCRIPTION
**Pull request by nschlemm**
...on https://github.com/alanjds/drf-nested-routers/issues/15

### CODE REVIEW

**Comment by jgirdner** [comment]
Are there any documents on how to use this?  I need to do a three level nest and can't seem to figure it out.  Right now I have.

client >> maildrops

and I need

client >> maildrops >> recipients

Any help would be much appreciated.  Below is my URLs

```
from django.conf.urls import patterns, include, url
from views import ClientViewSet, PrivateLabelViewSet, MailDropViewSet, CallViewSet, LeadViewSet, ScriptViewSet, PromptViewSet
from rest_framework_nested import routers
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'clients', ClientViewSet, base_name='clients')
router.register(r'privatelabels', PrivateLabelViewSet, base_name='privatelabels')

client_router = routers.NestedSimpleRouter(router, r'clients', lookup='client')
client_router.register(r'maildrops', MailDropViewSet, base_name='maildrops')
client_router.register(r'calls', CallViewSet, base_name='calls')
client_router.register(r'leads', LeadViewSet, base_name='leads')

privatelabel_router = routers.NestedSimpleRouter(router, r'privatelabels', lookup='privatelabel')
privatelabel_router.register(r'scripts', ScriptViewSet, base_name='scripts')
privatelabel_router.register(r'prompts', PromptViewSet, base_name='prompts')

urlpatterns = patterns(
    '',
    url(r'^', include(router.urls)),
    url(r'^', include(client_router.urls)),
    url(r'^', include(privatelabel_router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
    )
```

**Comment by jgirdner** [comment]
Nevermind.  Got it figured out and it works perfectly.

**Comment by alanjds** [comment]
Yeah... existing docs sucks. Happy that it works. Sad because you taught
that it was broken because of missing docs.

**Comment by jgirdner** [comment]
I just sent a pull request to update the readme with a full example of nesting 3 levels deep.  Thanks for your work on this project.

**Pull request merged**
